steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-product-api:latest'
      - '-f'
      - 'Services/Product/CRM.Product.Api/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-product-api:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zapcrm-product-api'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-product-api:latest'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'ConnectionStrings__PostgreSql=Host=136.118.121.105;Port=5432;Username=postgres;Password=Pg@Secret2026!;Database=zap_ecosystem,ASPNETCORE_ENVIRONMENT=Production,Jwt__Secret=a_very_secret_default_key_at_least_32_chars_long_1234567890,Jwt__Issuer=CRM.Authentication.Api,Jwt__Audience=CRM.GateWay.Api'

images:
  - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-product-api:latest'
