steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/pendogo-v1-6317/CRM-repo/CRM-report-api:latest', '-f', 'Services/Report/CRM.Report.Api/Dockerfile', '.']
images:
- 'asia-southeast1-docker.pkg.dev/pendogo-v1-6317/CRM-repo/CRM-report-api:latest'

