steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-customer-api:latest'
      - '-f'
      - 'Services/Customer/CRM.Customer.Api/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-customer-api:latest'

images:
  - 'asia-southeast1-docker.pkg.dev/zapcrm-492101/crm-repo/zapcrm-customer-api:latest'
