<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZAP.BackgroundWorker.Infrastructure\ZAP.BackgroundWorker.Infrastructure.csproj" />
    <ProjectReference Include="..\ZAP.BackgroundWorker.Application\ZAP.BackgroundWorker.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\BuildingBlocks\ZAP.BuildingBlocks\ZAP.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
