<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CRM.Customer.Domain\CRM.Customer.Domain.csproj" />
    <ProjectReference Include="..\CRM.Customer.Application\CRM.Customer.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="MongoDB.Bson" Version="3.7.0" />
	  <PackageReference Include="MongoDB.Driver" Version="3.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseAppHost>false</UseAppHost>
	  <!-- giảm file lock khi dev -->
  </PropertyGroup>

</Project>
