name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Configure Docker'
      run: gcloud auth configure-docker

    - name: 'Build and Push Container'
      run: |
        docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/zap-identity-api:${{ github.sha }} -f services/Zap.Identity.Api/Dockerfile .
        docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/zap-identity-api:${{ github.sha }}

    - name: 'Deploy to Cloud Run'
      run: |
        gcloud run deploy zap-identity-api \
          --image gcr.io/${{ vars.GCP_PROJECT_ID }}/zap-identity-api:${{ github.sha }} \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080
